[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = ""

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/providers/reset-password"
  to = "/.netlify/functions/reset-password"
  status = 200

[[redirects]]
  from = "/providers/new"
  to = "/.netlify/functions/provider-new"
  status = 200

[[redirects]]
  from = "/providers/:provider_id"
  to = "/.netlify/functions/provider?provider_id=:provider_id"
  status = 200

[[redirects]]
  from = "/providers/:provider_id/admin"
  to = "/.netlify/functions/provider-admin?provider_id=:provider_id"
  status = 200

[[redirects]]
  from = "/providers/:provider_id/forgot-password"
  to = "/.netlify/functions/provider-password-reset"
  status = 200

[[redirects]]
  from = "/providers/:provider_id/admin/stats"
  to = "/.netlify/functions/provider-stats?provider_id=:provider_id"
  status = 200

[[redirects]]
  from = "/providers/:provider_id/admin/profile"
  to = "/.netlify/functions/provider-profile?provider_id=:provider_id"
  status = 200
  force = true

[[redirects]]
  from = "/providers/:provider_id/admin/:lead_id"
  to = "/.netlify/functions/provider-lead?provider_id=:provider_id&lead_id=:lead_id"
  status = 200

[[redirects]]
  from = "/providers/:provider_id/login"
  to = "/.netlify/functions/provider-login?provider_id=:provider_id"
  status = 200

[[redirects]]
  from = "/providers/:provider_id/logout"
  to = "/.netlify/functions/provider-logout?provider_id=:provider_id"
  status = 200
