[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = ""

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/providers/:provider_id"
  to = "/.netlify/functions/provider?provider_id=:provider_id"
  status = 200
